version: 2
jobs:
  test_py2:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run: python setup.py install
      - run: python -m unittest discover
  test_py3:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - run: python setup.py install
      - run: python -m unittest discover
workflows:
  version: 2
  test:
    jobs:
      - test_py2
      - test_py3